# Generated by Django 6.0.2 on 2026-03-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttgen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name': 'Division', 'verbose_name_plural': 'Divisions'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructors'},
        ),
        migrations.AlterModelOptions(
            name='meetingtime',
            options={'verbose_name': 'Meeting Time', 'verbose_name_plural': 'Meeting Times'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AddField(
            model_name='instructor',
            name='max_batches_per_week',
            field=models.IntegerField(default=4, help_text='Maximum number of lab batches this teacher can handle'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='max_lecture_divisions',
            field=models.IntegerField(default=2, help_text='Maximum number of divisions for lectures'),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='slot_type',
            field=models.CharField(choices=[('LECTURE', '1-hour Lecture Slot'), ('LAB', '2-hour Lab Slot')], default='LECTURE', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('LECTURE', 'Lecture Hall'), ('LAB', 'Laboratory')], default='LECTURE', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together={('division_name', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='meetingtime',
            unique_together={('day', 'time', 'slot_type')},
        ),
    ]
