# Generated by Django 6.0.2 on 2026-03-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttgen', '0002_alter_batch_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_elective',
            field=models.BooleanField(default=False, help_text='Is this an elective course?'),
        ),
        migrations.AddField(
            model_name='section',
            name='elective_group',
            field=models.CharField(blank=True, help_text='G1 or G2 for electives', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='is_elective',
            field=models.BooleanField(default=False, help_text='Is this an elective section?'),
        ),
    ]
